name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Lua
      uses: xpol/setup-lua@v0.2
      with:
        lua-version: 5.3.5
    - name: Check that main.lua has no errors
      run: lua5.3 main.lua
    - name: Check that test.lua has no errors
      run: lua5.3 test.lua
